### ISSUE TITLE
Version checker cannot cope with single digit strings in package.json

### ISSUE THREAD

**Issue by samphilipd** [shakacode/react_on_rails#489] opened 2016-07-26 13:26 UTC
Steps to reproduce:
1. In client/package.json specify version: `"react-on-rails": "^6"`
2. In root path run `bundle exec rails server`

Expected behaviour:
- Should run fine

Actual behaviour:
- Crashes with:

```
/Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.0.5/lib/react_on_rails/version_checker.rb:69:in `major': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.0.5/lib/react_on_rails/version_checker.rb:21:in `warn_if_gem_and_node_package_versions_differ'
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/react_on_rails-6.0.5/lib/react_on_rails/engine.rb:5:in `block in <class:Engine>'
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:396:in `instance_exec'
    from /Users/sam/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:396:in `block in make_lambda'
(... trace truncated ...)
```

The problem is on `version_checker.rb` line 69. The regex should probably be more like this: `raw.match(/(\d+)(\.|\z)/)[1]`

**Comment by justin808** [comment] 2016-07-27 00:25
Hi @samphilipd!

Any chance that you can help us with a PR (including a test?)

CC: @robwise

**Comment by RKushnir** [comment] 2017-08-04 08:30
This issue is still present in 8.0.6.
I installed the js package as follows: `yarn add react-on-rails@8`, and the gem tries to parse "8" with "major.minor.patch" regex.

**Comment by RKushnir** [comment] 2017-08-04 08:34
So it's been reverted to the broken version here https://github.com/shakacode/react_on_rails/commit/251fa75498a333d11e4c76d06b4065c951b39817#diff-0c19a2d62c614c09b80b965b9aa73eac

This issue needs to be re-opened.

**Comment by justin808** [comment] 2017-08-04 19:46
@RKushnir We require the full X.Y.Z version number to stay in sync between the gemfile and the package.json. The reason:

In case we deploy a change that has a bug, we may need to update both the Gem and the NPM version and require both are at the same exact version.

**Comment by RKushnir** [comment] 2017-08-04 21:12
@justin808 I understand that, but the parser should tell what the problem is, not just fail with a random exception. To figure it out, I had to explore the gem source and debug the reason of failure, quite inefficient.

**Comment by justin808** [comment] 2017-08-04 23:13
@RKushnir Any chance that you can submit a PR for a better error message?

**Comment by justin808** [comment] 2017-08-04 23:13
u

**Comment by justin808** [comment] 2017-11-10 01:41
Closing for lack of interest.

**Closed by justin808** 2017-11-10 01:41 UTC
Labels: bug
