### ISSUE TITLE
Build on production env at DigitalOcean using Capistrano

### ISSUE THREAD

**Issue by r0st1kuzh** [shakacode/react_on_rails#304] opened 2016-03-02 19:22 UTC
Hello guys, 
Really great work has been done on this project.
Could you also provide some instructions how to use react_on_rails with Capistrano.
I need to deploy an application and can't find information about that anywhere.

I would appreciate!

**Comment by justin808** [comment] 2016-03-02 19:28
@r0st1kuzh I only use Heroku for now, although I do have discourse sites using digital ocean.

When you find some info, can you please submit a doc PR with details?

**Comment by r0st1kuzh** [comment] 2016-03-02 20:00
@justin808 sure! Definitely will do

**Comment by r0st1kuzh** [comment] 2016-03-02 22:32
@justin808 Hey, just noticed that during deployment to the DO, npm install task is not triggered automatically. I don't know if it does on Heroku, but how is better to add that task from your perspective?

**Comment by r0st1kuzh** [comment] 2016-03-02 23:38
I've tried to configure additionally https://github.com/capistrano/npm but unfortunately no success...(

**Comment by SqueezedLight** [comment] 2016-03-06 20:31
@r0st1kuzh do you have any particular question? I deployed ReactOnRails Apps with capistrano and have some experience with it. Any specific errors/problems? All in all i'd recommend the following:
- Be sure that your Capistrano deployment works with a simple Rails App (as simple as possible - without ReactOnRails or Node). 
- Then get Node/npm up and running on the server. Check versions (npm v3.6.0 and node v5.5.0)
- Before you deploy your ReactOnRails App, be sure everything works fine in dev mode. 
- Start without Server side rendering - this makes debugging much easier.

I know this is far away from some magical tricks. But things are getting so much easier if you go step by step. I did not experience problems only caused by ReactOnRails and therefore it should go fairly straightforward.

**Comment by justin808** [comment] 2016-03-07 08:30
@SqueezedLight @r0st1kuzh Can we close this issue? I want to save issues for bugs and enhancements. We can take discussions to http://forum.shakacode.com/.

Thanks!

**Comment by SqueezedLight** [comment] 2016-03-07 08:31
Sure!

**Closed** 2016-03-07 08:32 UTC
Labels: question

**Comment by r0st1kuzh** [comment] 2016-03-07 21:30
@SqueezedLight Hello, it seems that I am missing some configuration which is related to the npm install. I have checked those things that you mentioned above: 
1) works
2) https://www.dropbox.com/s/yw0aqtyicry5ze5/Screenshot%202016-03-07%2023.29.21.png?dl=0
3) works
4) i was using generator with -R and -S options
Here is the error I am getting. 
https://www.dropbox.com/s/piqnd5a1ruknway/Screenshot%202016-03-07%2023.25.19.png?dl=0
Would really appreciate if you will be able to help me.

**Comment by fatehwaharp** [comment] 2016-11-10 06:52
I've tried to push the basic ReactOnRails sample to digital ocean, and currently stuck with it,

using npm v3.10.9 and node v7.1.0

the error log is 
```
Command failed with status (1): [cd client && npm run build:production...]
 DEBUG [ce0fdd4a] 	/home/deploy/test-react/shared/bundle/ruby/2.3.0/gems/react_on_rails-6.1.2/lib/tasks/assets.rake:33:in `block (3 levels) in <top (required)>'
/home/deploy/test-react/shared/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/deploy/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
(See full trace by running task with --trace)
  INFO ---------------------------------------------------------------------------
  INFO START 2016-11-10 14:30:39 +0800 cap production deploy
  INFO ---------------------------------------------------------------------------
 DEBUG [990c9b5c] Running [ -d $HOME/.rbenv/versions/2.3.1 ] as deploy@128.199.224.194
 DEBUG [990c9b5c] Command: [ -d $HOME/.rbenv/versions/2.3.1 ]
 DEBUG [990c9b5c] Finished in 0.695 seconds with exit status 0 (successful).
  INFO [8ab82675] Running /usr/bin/env mkdir -p /tmp/test-react/ as deploy@128.199.224.194
 DEBUG [8ab82675] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" ; /usr/bin/env mkdir -p /tmp/test-react/ )
  INFO [8ab82675] Finished in 0.668 seconds with exit status 0 (successful).
 DEBUG Uploading /tmp/test-react/git-ssh.sh 0.0%
  INFO Uploading /tmp/test-react/git-ssh.sh 100.0%
  INFO [0f611e3f] Running /usr/bin/env chmod +rx /tmp/test-react/git-ssh.sh as deploy@128.199.224.194
 DEBUG [0f611e3f] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" ; /usr/bin/env chmod +rx /tmp/test-react/git-ssh.sh )
  INFO [0f611e3f] Finished in 0.105 seconds with exit status 0 (successful).
  INFO [6112d860] Running /usr/bin/env git ls-remote --heads git@github.com:fatehwaharp/test-do-rails-react.git as deploy@128.199.224.194
 DEBUG [6112d860] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/test-react/git-ssh.sh" ; /usr/bin/env git ls-remote --heads git@github.com:fatehwaharp/test-do-rails-react.git )
 DEBUG [6112d860] 	16e43dd839031bf34f5719f0606b53b5f5c943c9	refs/heads/master
  INFO [6112d860] Finished in 3.455 seconds with exit status 0 (successful).
  INFO [fcca6f21] Running /usr/bin/env mkdir -p /home/deploy/test-react/shared /home/deploy/test-react/releases as deploy@128.199.224.194
 DEBUG [fcca6f21] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" ; /usr/bin/env mkdir -p /home/deploy/test-react/shared /home/deploy/test-react/releases )
  INFO [fcca6f21] Finished in 0.142 seconds with exit status 0 (successful).
  INFO [fb21929c] Running /usr/bin/env mkdir -p /home/deploy/test-react/shared/bin /home/deploy/test-react/shared/log /home/deploy/test-react/shared/tmp/pids /home/deploy/test-react/shared/tmp/cache /home/deploy/test-react/shared/tmp/sockets /home/deploy/test-react/shared/vendor/bundle /home/deploy/test-react/shared/public/system /home/deploy/test-react/shared/public/assets as deploy@128.199.224.194
 DEBUG [fb21929c] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" ; /usr/bin/env mkdir -p /home/deploy/test-react/shared/bin /home/deploy/test-react/shared/log /home/deploy/test-react/shared/tmp/pids /home/deploy/test-react/shared/tmp/cache /home/deploy/test-react/shared/tmp/sockets /home/deploy/test-react/shared/vendor/bundle /home/deploy/test-react/shared/public/system /home/deploy/test-react/shared/public/assets )
  INFO [fb21929c] Finished in 0.101 seconds with exit status 0 (successful).
  INFO [0325faa6] Running /usr/bin/env mkdir -p /home/deploy/test-react/shared/config as deploy@128.199.224.194
 DEBUG [0325faa6] Command: ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.3.1" ; /usr/bin/env mkdir -p /home/deploy/test-react/shared/config )
```
