### ISSUE TITLE
Components aren't unmounted when Turbolinks cache is disabled

### ISSUE THREAD

**Issue by volkanunsal** [shakacode/react_on_rails#629] opened 2016-11-30 14:17 UTC
This issue is related to #610. Listening to `turbolinks:before-cache` event results in component not being unmounted when the cache is disabled. I propose using `turbolinks:before-visit` event in addition to it, which would cover all the bases. (However, if both events are fired off consecutively, this approach might cause problems. It's worth investigating further.)

**Comment by justin808** [comment] 2016-11-30 22:06
@volkanunsal Please keep researching this. Eventually, we might want to create a customized offshoot of turbolinks that can work with react-router and code-splitting by routes.

**Comment by szyablitsky** [comment] 2016-12-09 02:38
https://github.com/shakacode/react_on_rails/pull/425 fixes for me the 'flickering' of component which is rendered on every page when navigating between pages.
So changing `turbolinks:before-render` to `turbolinks:before-cache` fixes one problem but has a regression on the other.

**Comment by justin808** [comment] 2016-12-09 03:53
@szyablitsky @volkanunsal The community will greatly appreciate any research into this matter, and a PR!

**Comment by volkanunsal** [comment] 2016-12-09 04:09
@justin808 I've been meaning to come back to this. I'm going to look into it tomorrow!

**Comment by volkanunsal** [comment] 2016-12-11 16:25
I discovered that `turbolinks:before-visit` is called even earlier than `turbolinks:before-cache`, and it's never omitted like `turbolinks:before-cache` is, even when cache is disabled. So It can easily be used to cover all cases. I'm going to submit a PR replacing `turbolinks:before-cache` with `turbolinks:before-visit`, unless there are concerns about backward compatibility.

**Comment by szyablitsky** [comment] 2016-12-12 01:34
may be we should make this configurable?
in our project we use `turbolinks:before-render` to minimize the absence time for the component which is rendered on all pages of the application

**Comment by volkanunsal** [comment] 2016-12-12 02:36
@szyablitsky What version of react are you using? In 15.2.x I get the error discussed in #610

**Comment by szyablitsky** [comment] 2016-12-12 04:05
Right now we're using react@15.4.1 & react-on-rails@6.2.0
I've seen this error before, and did not know this can be related to turbolinks. I do not see this error in our application anymore.
Ha-ha. As it turns out react-on-rails@6.2.0 already have merged using `turbolinks:before-cache`, despite changelog, which says it was merged only in 6.2.1. That's why we do not have "The node you're attempting to unmount was rendered by another copy of React" problem. But we have 'flickering' components problem again.

**Comment by volkanunsal** [comment] 2016-12-12 14:34
Disable Turbolinks cache with a meta tag. That should take care of it.

**Comment by volkanunsal** [comment] 2016-12-12 19:10
@szyablitsky I mean disable the cache after the latest PR lands. You shouldn't disable it when still using `turbolinks:before-cache` event hook.

**Comment by szyablitsky** [comment] 2017-01-12 08:31
@volkanunsal disabling turbolinks cache doesn't solve "flickering" components problem.
React-rails gem has the same issue https://github.com/reactjs/react-rails/issues/607 and they also don't know how to handle it.

**Comment by volkanunsal** [comment] 2017-01-12 13:50
@szyablitsky A potential solution is to use fake content at the mount point. It would look something like the component, and have the same dimensions.

**Closed** 2017-01-12 13:50 UTC
Labels: discussion

**Comment by szyablitsky** [comment] 2017-01-13 01:58
@volkanunsal thank you for the idea. This can be used as a partial solution.

**Comment by szyablitsky** [comment] 2017-02-03 13:41
I think the best solution is to modify ReactDOM's `unmountComponentAtNode` and more specifically `unmountComponentFromNode` so it can bypass emptying of the container https://github.com/facebook/react/blob/8791325db03725ef4801fc58b35a3bb4486a8904/src/renderers/dom/stack/client/ReactMount.js#L190 
May be additional boolean parameter like `doNotEmptyContainer`. And use this parameter in our Turbolinks handlers.
