### ISSUE TITLE
react_on_rails:assets:symlink_non_digested_assets crashes when sprockets-manifest-*.json is missing

### ISSUE THREAD

**Issue by UberMouse** [shakacode/react_on_rails#429] opened 2016-05-23 01:38 UTC
In the event you are missing the `sprockets-manifest-*.json` the assets:precompile tasks fails because it tries to parse the JSON file using a `nil` path. I made it not crash by checking if the `manifest_path` variable is present before running the task but I'm not sure if that is solving the problem or putting a bandaid over it so I haven't made a PR.

**Comment by justin808** [comment] 2016-05-23 02:42
@UberMouse is this a general problem without React on Rails? I don't see the connection with what we're doing with precompilation and this issue.

**Comment by UberMouse** [comment] 2016-05-23 02:44
Well it's crashing inside a React on Rails rake task? I fixed it for me by doing this 

https://github.com/UberMouse/react_on_rails/commit/db19754079e50ddd7ace4b003f06bc626cad1a11

**Comment by justin808** [comment] 2016-05-23 02:44
OK, I see the issue is with this code in https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake

```ruby
    desc "Creates non-digested symlinks for the assets in the public asset dir"
    task symlink_non_digested_assets: :"assets:environment" do
      if ReactOnRails.configuration.symlink_non_digested_assets_regex
        manifest_path = Dir.glob(ReactOnRails::assets_path.join(".sprockets-manifest-*.json"))
                          .first
        manifest_data = JSON.load(File.new(manifest_path))

        manifest_data["assets"].each do |logical_path, digested_path|
          regex = ReactOnRails.configuration.symlink_non_digested_assets_regex
          if logical_path =~ regex
            full_digested_path = ReactOnRails::assets_path.join(digested_path)
            full_nondigested_path = ReactOnRails::assets_path.join(logical_path)
            extension = full_digested_path.extname
            full_digested_gz_path = full_digested_path.sub_ext("#{extension}.gz")
            full_nondigested_gz_path = full_nondigested_path.sub_ext("#{extension}.gz")
            ReactOnRails::symlink_file(full_digested_path, full_nondigested_path)
            ReactOnRails::symlink_file(full_digested_gz_path, full_nondigested_gz_path)
          end
        end
      end
    end
```

I'm guessing we should just check if that file does not exist, and the maybe do nothing? I'm really not sure. We need to ask @alleycat-at-git .

**Comment by UberMouse** [comment] 2016-05-23 02:45
That is what I did to fix it. Not sure if it's the best approach, I'm not sure what the task does, but it resolved my issue. I'm running the gem off my fork in the meantime so I can do deployments.

**Comment by alexeykarasev** [comment] 2016-05-23 14:11
@UberMouse Thanks for the report! I will look into that. In the meantime, can you give me the case, why you have no manifest.json file?

**Comment by nratter** [comment] 2016-05-23 19:58
@alexeykarasev manifest.json was renamed in sprockets. Also, it's `.sprockets-manifest-*.json`, not `sprockets-manifest-*.json`. I'm having the same issue. This can be easily replicated using `rake assets:clobber`. The problem is, the assets directory (along with the files) is completely removed when you clobber, so this code won't know where to point to.

**Comment by alleycat-at-git** [comment] 2016-05-24 07:26
@UberMouse @nratter check out [this PR](https://github.com/shakacode/react_on_rails/pull/431) does it work now?

**Comment by nratter** [comment] 2016-05-24 17:47
@alleycat-at-git haven't tried but looks good 👍

**Comment by justin808** [comment] 2016-05-25 05:29
Fixed in v6!

**Closed by justin808** 2016-05-25 05:29 UTC
