### ISSUE TITLE
uninitialized constant `ReactOnRails::Configuration::Webpacker`

### ISSUE THREAD

**Issue by adriangohjw** [shakacode/react_on_rails#1621] opened 2024-05-20 15:33 UTC
## Environment
Ruby version: 3.3.1
Rails version: 7.1.3.2
Shakapacke version: 8.0.0
React on Rails version: 14.0.0

## Expected behavior
Running `rails s` should start the server successfully

## Actual behavior
Facing this error and server refuse to start up
```
.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/react_on_rails-14.0.0/lib/react_on_rails/configuration.rb:261:in `shakapacker_precompile?': uninitialized constant ReactOnRails::Configuration::Webpacker (NameError)

Webpacker.config.shakapacker_precompile?
```

## Details

Changing `Webpacker.config.shakapacker_precompile?` to `Shakapacker.config.shakapacker_precompile?` seem to fix the issue (on my end, at least)

https://github.com/shakacode/react_on_rails/blob/36f342c6086718289e4d66d0eea2fbf1f6334a8d/lib/react_on_rails/configuration.rb#L258-L262

**Comment by justin808** [comment] 2024-05-21 07:11
@adriangohjw can you update spec/dummy app to use Shakapacker v8?

**Comment by adriangohjw** [comment] 2024-05-21 08:17
@justin808 done! https://github.com/shakacode/react_on_rails/pull/1622/commits/e1c1b2d4512a23cd63f5b91a7fd82dafc5c7e2c4

**Comment by 4-Eyes** [comment] 2024-06-23 01:29
I can confirm this bug still exists, event though the associated [PR](https://github.com/shakacode/react_on_rails/pull/1622) has been closed. As a workaround until this is fixed, I've just put an initializer in my app that sets `Webpacker` to `Shakapacker`, as shown below:

```rb
# app/config/initializers/webpacker.rb
Webpacker = Shakapacker
```

**Comment by sophiedeziel** [comment] 2024-06-23 04:01
I confirm @4-Eyes 's hack worked for me.

**Comment by aarestad** [comment] 2024-06-24 16:29
For the record, it looks like a fix was supposed to have be merged in https://github.com/shakacode/react_on_rails/pull/1629.

**Comment by justin808** [comment] 2024-06-25 07:19
#1622 will fix this.

**Closed** 2024-06-28 21:19 UTC
Labels: bug
